set(CPACK_PACKAGE_VENDOR "swagger.io")
set(CPACK_PACKAGE_CONTACT "Ultimaker <info@ultimaker.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Ultimaker swagger pages")
set(CPACK_PACKAGE_VERSION "${RELEASE_VERSION}")
set(CPACK_GENERATOR "DEB")

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE all)

include(CPack)
