set(CPACK_PACKAGE_VENDOR "swagger.io")
set(CPACK_PACKAGE_CONTACT "Ultimaker <info@ultimaker.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Ultimaker swagger pages")
set(CPACK_PACKAGE_VERSION_MAJOR 9999)
set(CPACK_PACKAGE_VERSION_MINOR 99)
set(CPACK_PACKAGE_VERSION_PATCH 99)
set(CPACK_GENERATOR "DEB")

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE all)

include(CPack)
